export default {
  Python: 'python.svg',
  PyTorch: 'pytorch.svg',
  NumPy: 'numpy.svg',
  SciPy: 'scipy.svg',
  Matplotlib: 'matplotlib.svg',
  Optuna: ['optuna.png', ''],
  LaTeX: 'latex.png',
  R: 'r.svg',
  Pygame: ['pygame.png', ''],
  OpenCV: 'opencv.png',
  'Raspberry Pi': 'raspberrypi.png',
  Arduino: 'arduino.png',
  MATLAB: 'matlab.png',
  Simulink: 'simulink.png',
  Excel: 'excel.svg',
  VBA: 'vba.png',
  PHP: ['php.svg', ''],
  WordPress: 'wordpress.svg',
  Notion: 'notion.svg',
  'Google Calendar': 'googlecalendar.svg',
  n8n: ['n8n.png', ''],
  Jupyter: 'jupyter.svg',
  pandas: 'pandas.svg',
  statsmodels: 'statsmodels.svg',
  COMSOL: ['comsol.svg', ''],
  CVXPY: ['cvxpy.png', ''],
  'Altair Inspire': ['altair.svg', 'Inspire']
};
